import { useMemo, useState } from "react";
import { BookOpen, CalendarClock, Check, ChevronLeft, ChevronRight, Clock3, Edit3, Heart, Library, Plus, RotateCcw, Sparkles, Target, X } from "lucide-react";

type BookStatus = "Reading" | "Want to read" | "Finished";
type Book = { id: number; title: string; author: string; cover: string; status: BookStatus; pages: number; read: number; notes: string; quote: string; favorite: boolean };

const INITIAL_BOOKS: Book[] = [
  { id: 1, title: "Atomic Habits", author: "James Clear", cover: "#f6b6c8", status: "Reading", pages: 320, read: 180, notes: "Small systems make progress visible.", quote: "Every action is a vote for the person you wish to become.", favorite: true },
  { id: 2, title: "Deep Work", author: "Cal Newport", cover: "#b9c8f7", status: "Want to read", pages: 296, read: 0, notes: "", quote: "", favorite: false },
  { id: 3, title: "The Design of Everyday Things", author: "Don Norman", cover: "#b8e3d0", status: "Finished", pages: 368, read: 368, notes: "Design should make the right action obvious.", quote: "", favorite: false },
];

export function VisualBookshelf() {
  const [books, setBooks] = useState(INITIAL_BOOKS);
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const selectedBook = books.find((book) => book.id === selectedId);
  const updateBook = (patch: Partial<Book>) => setBooks((current) => current.map((book) => book.id === selectedId ? { ...book, ...patch } : book));

  return <section className="card p-5 md:p-6">
    <div className="flex items-start justify-between gap-3 mb-5"><div><div className="flex items-center gap-2 text-[var(--accent)]"><Library size={18} /><span className="text-xs uppercase tracking-wider font-semibold">Reading tracker</span></div><h2 className="text-xl font-bold mt-1">Your bookshelf</h2></div><button className="btn-secondary text-xs" onClick={() => setSelectedId(null)}><Plus size={15} /> Add book</button></div>
    <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
      {books.map((book) => { const progress = Math.round((book.read / book.pages) * 100); return <button key={book.id} className="text-left p-3 rounded-2xl border border-[var(--border)] hover:border-[var(--accent)] transition-colors" onClick={() => setSelectedId(book.id)}><div className="h-28 rounded-xl flex items-center justify-center p-4 text-center shadow-inner" style={{ background: book.cover }}><BookOpen size={28} className="text-white/90" /></div><div className="flex items-start gap-2 mt-3"><div className="min-w-0 flex-1"><div className="font-bold text-sm truncate">{book.title}</div><div className="text-[11px] text-[var(--text-muted)] truncate">{book.author}</div></div>{book.favorite && <Heart size={14} className="fill-[var(--accent)] text-[var(--accent)] shrink-0" />}</div><span className="badge mt-2 bg-[var(--surface-2)] text-[var(--text-muted)]">{book.status}</span><div className="h-1.5 bg-[var(--surface-2)] rounded-full overflow-hidden mt-3"><div className="h-full bg-[var(--accent)]" style={{ width: `${progress}%` }} /></div><div className="text-[10px] text-[var(--text-muted)] mt-1">{book.read} / {book.pages} pages</div></button>; })}
    </div>
    {selectedBook && <div className="mt-5 p-4 rounded-2xl bg-[var(--surface-2)] border border-[var(--border)]"><div className="flex items-center justify-between"><div><div className="text-sm font-bold">Edit {selectedBook.title}</div><div className="text-xs text-[var(--text-muted)]">Keep the useful parts close.</div></div><button className="p-2 text-[var(--text-muted)]" onClick={() => setSelectedId(null)} aria-label="Close book editor"><X size={16} /></button></div><div className="grid md:grid-cols-3 gap-3 mt-4"><label className="label">Pages read<input className="input mt-1" type="number" min="0" max={selectedBook.pages} value={selectedBook.read} onChange={(event) => updateBook({ read: Math.min(selectedBook.pages, Number(event.target.value)) })} /></label><label className="label">Status<select className="input mt-1" value={selectedBook.status} onChange={(event) => updateBook({ status: event.target.value as BookStatus })}><option>Reading</option><option>Want to read</option><option>Finished</option></select></label><label className="label flex items-center gap-2 mt-7"><input type="checkbox" checked={selectedBook.favorite} onChange={(event) => updateBook({ favorite: event.target.checked })} className="accent-[var(--accent)]" /> Favorite</label></div><label className="label mt-3">Notes<textarea className="input mt-1 min-h-16 resize-y" value={selectedBook.notes} onChange={(event) => updateBook({ notes: event.target.value })} placeholder="What do you want to remember?" /></label><label className="label mt-3">Favorite quote<textarea className="input mt-1 min-h-16 resize-y" value={selectedBook.quote} onChange={(event) => updateBook({ quote: event.target.value })} placeholder="Capture a line worth returning to." /></label></div>}
  </section>;
}

type Flashcard = { question: string; answer: string; interval: number };
const INITIAL_CARDS: Flashcard[] = [{ question: "What is the derivative of sin(x)?", answer: "cos(x)", interval: 1 }, { question: "What does HTTP stand for?", answer: "Hypertext Transfer Protocol", interval: 1 }, { question: "Define spaced repetition.", answer: "Reviewing information at increasing intervals to improve long-term recall.", interval: 1 }];

export function FlashcardWidget() {
  const [cards, setCards] = useState(INITIAL_CARDS);
  const [index, setIndex] = useState(0);
  const [flipped, setFlipped] = useState(false);
  const card = cards[index];
  const rateCard = (multiplier: number) => { setCards((current) => current.map((item, position) => position === index ? { ...item, interval: Math.max(1, Math.round(item.interval * multiplier)) } : item)); setFlipped(false); setIndex((value) => (value + 1) % cards.length); };

  return <section className="card p-5 md:p-6"><div className="flex items-start justify-between"><div><div className="flex items-center gap-2 text-[var(--accent)]"><Sparkles size={18} /><span className="text-xs uppercase tracking-wider font-semibold">Spaced repetition</span></div><h2 className="text-xl font-bold mt-1">Flashcards</h2></div><span className="badge bg-[var(--surface-2)]">{index + 1} / {cards.length}</span></div><button className="relative w-full h-48 mt-5 text-left [perspective:1000px]" onClick={() => setFlipped((value) => !value)} aria-label="Flip flashcard"><div className={`absolute inset-0 transition-transform duration-500 [transform-style:preserve-3d] ${flipped ? "[transform:rotateY(180deg)]" : ""}`}><div className="absolute inset-0 [backface-visibility:hidden] rounded-3xl border border-[var(--border)] bg-gradient-to-br from-[#fff5f8] to-[#f0efff] dark:from-[var(--surface-2)] dark:to-[var(--surface)] p-6 flex flex-col justify-between"><span className="text-xs text-[var(--text-muted)]">Question</span><span className="text-lg font-bold">{card.question}</span><span className="text-xs text-[var(--text-muted)]">Tap to reveal answer</span></div><div className="absolute inset-0 [backface-visibility:hidden] [transform:rotateY(180deg)] rounded-3xl border border-[var(--accent)] bg-[var(--accent-soft)] p-6 flex flex-col justify-between"><span className="text-xs text-[var(--text-muted)]">Answer</span><span className="text-lg font-bold">{card.answer}</span><span className="text-xs text-[var(--text-muted)]">Current interval: {card.interval} day{card.interval === 1 ? "" : "s"}</span></div></div></button><div className="grid grid-cols-3 gap-2 mt-4"><button className="btn-secondary text-xs" onClick={() => rateCard(1)}>Hard <span className="text-[var(--text-muted)]">1d</span></button><button className="btn-secondary text-xs" onClick={() => rateCard(2)}>Good <span className="text-[var(--text-muted)]">{card.interval * 2}d</span></button><button className="btn-primary text-xs" onClick={() => rateCard(3)}>Easy <span>{card.interval * 3}d</span></button></div><div className="flex justify-center gap-2 mt-3"><button className="p-2 text-[var(--text-muted)]" onClick={() => { setFlipped(false); setIndex((value) => (value - 1 + cards.length) % cards.length); }} aria-label="Previous card"><ChevronLeft size={17} /></button><button className="p-2 text-[var(--text-muted)]" onClick={() => { setFlipped(false); setIndex((value) => (value + 1) % cards.length); }} aria-label="Next card"><ChevronRight size={17} /></button></div></section>;
}

type CountdownItem = { title: string; date: string; type: string; priority: "High" | "Medium" | "Low"; progress: number };
const COUNTDOWNS: CountdownItem[] = [{ title: "Physics Exam", date: "2026-10-04", type: "Exam", priority: "High", progress: 68 }, { title: "Calculus presentation", date: "2026-10-16", type: "Project", priority: "Medium", progress: 42 }, { title: "History reading review", date: "2026-10-28", type: "Review", priority: "Low", progress: 84 }];

export function ExamCountdown() {
  const today = new Date();
  const items = useMemo(() => COUNTDOWNS.map((item) => ({ ...item, days: Math.max(0, Math.ceil((new Date(`${item.date}T12:00:00`).getTime() - today.getTime()) / 86_400_000)) })), [today.toDateString()]);
  return <section className="card p-5 md:p-6"><div className="flex items-start justify-between"><div><div className="flex items-center gap-2 text-[var(--accent)]"><CalendarClock size={18} /><span className="text-xs uppercase tracking-wider font-semibold">Planning</span></div><h2 className="text-xl font-bold mt-1">Exam & project countdown</h2></div><button className="btn-secondary text-xs"><Plus size={15} /> Add date</button></div><div className="space-y-3 mt-5">{items.map((item) => <div key={item.title} className="p-4 rounded-2xl border border-[var(--border)]"><div className="flex items-start gap-3"><div className="w-10 h-10 rounded-xl bg-[var(--surface-2)] flex items-center justify-center shrink-0"><Target size={18} className="text-[var(--accent)]" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="font-bold text-sm">{item.title}</span><span className="badge bg-[var(--surface-2)] text-[var(--text-muted)]">{item.type}</span><span className={`badge ${item.priority === "High" ? "bg-red-50 text-red-600" : item.priority === "Medium" ? "bg-yellow-50 text-yellow-700" : "bg-green-50 text-green-700"}`}>{item.priority}</span></div><div className="flex items-center gap-2 text-xs text-[var(--text-muted)] mt-1"><Clock3 size={13} /> {item.days === 0 ? "Today" : `${item.days} days remaining`} <span>•</span> {new Date(`${item.date}T12:00:00`).toLocaleDateString(undefined, { month: "short", day: "numeric" })}</div><div className="flex items-center gap-3 mt-3"><div className="h-2 flex-1 rounded-full bg-[var(--surface-2)] overflow-hidden"><div className="h-full rounded-full bg-[var(--accent)]" style={{ width: `${item.progress}%` }} /></div><span className="text-xs font-semibold">{item.progress}%</span></div></div></div></div>)}</div></section>;
}
